### ISSUE TITLE
Broken Links - Public Talks README.md

### ISSUE THREAD

**Issue by StefGehring** [miraisolutions/PublicTalks#1]
Fix broken links:

UseR 2019! Toulouse https://github.com/miraisolutions/PublicTalks/blob/master/20190710_CompareWith.pdf.pdf
R meet-up, Zurich https://github.com/miraisolutions/PublicTalks/blob/master/20161208_Use_R_in_Finance.pdf

**Comment by fvitalini** [comment]
created PR to fix this https://github.com/miraisolutions/PublicTalks/pull/2

**Comment by fvitalini** [comment]
@RolandASc not sure who should take care of the merging
